name: 'Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - 'library-b/**'
  pull_request:
    paths:
      - 'library-b/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: ./library-b
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: library-b
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
